# Generated by Django 5.1.4 on 2025-01-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalWaves_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='criminal_record',
            new_name='CriminalRecord',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='dob',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='facebook_id',
            new_name='FacebookID',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='linkedin_username',
            new_name='LinkedinUsername',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='married',
            new_name='Married',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='other_name',
            new_name='OtherName',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='own_property',
            new_name='OwnProperty',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='phone_number',
            new_name='PhoneNumber',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='sex',
            new_name='Sex',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='twitter_id',
            new_name='TwitterID',
        ),
    ]
