# Generated by Django 5.1.4 on 2025-03-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalWaves_App', '0002_rename_address_userinformation_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToFixCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APIType', models.TextField(max_length=30, unique=True)),
                ('TipToFix', models.TextField()),
            ],
        ),
    ]
