# Generated by Django 5.1.4 on 2025-03-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalWaves_App', '0004_confirmedresultsentries'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='PreviousScore',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
