# Generated by Django 5.1.4 on 2025-03-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalWaves_App', '0005_userinformation_previousscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='FacebookID',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='LinkedinUsername',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='TwitterID',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
