# Generated by Django 5.1.4 on 2025-03-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalWaves_App', '0006_alter_userinformation_facebookid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='FacebookID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='LinkedinUsername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='TwitterID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
