# Generated by Django 5.1.4 on 2025-03-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalWaves_App', '0007_alter_userinformation_facebookid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='FacebookID',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='LinkedinUsername',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='TwitterID',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
