# Generated by Django 5.1.4 on 2025-03-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalWaves_App', '0003_howtofixcategories_confirmedresultsentries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='howtofixcategories',
            old_name='Flag',
            new_name='APIType',
        ),
        migrations.DeleteModel(
            name='ConfirmedResultsEntries',
        ),
    ]
